name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    uses: fxp/deploy-app-action/.github/workflows/pages.yml@main
    with:
      project_name: the-stall
    secrets: inherit
